//! Run Chopin using a pre-generated bivariate KZG setup loaded from disk.
//!
//! This example expects setup keys generated by `bivariatekzg_test_setup`.
//!
//! Run with: `cargo run --example chopin_from_setup --features io`

use std::{fs::OpenOptions, io::BufReader};

use ff::Field;
use nova_snark::{
  provider::{chopin::EvaluationEngine as ChopinEvaluationEngine, Bn256EngineBivariateKZG},
  spartan::polys::multilinear::MultilinearPolynomial,
  traits::{
    commitment::CommitmentEngineTrait, evaluation::EvaluationEngineTrait, Engine,
    TranscriptEngineTrait,
  },
};
use rand_core::OsRng;

type E = Bn256EngineBivariateKZG;

const KZG_KEY_DIR: &str = "bivariatekzg-setup";
const LABEL: &[u8; 4] = b"test";

fn main() {
  for log_n in 10..12 {
    let n = 1 << log_n;
    let path = format!("{KZG_KEY_DIR}/ck_{log_n}");
    let file = OpenOptions::new()
      .read(true)
      .open(&path)
      .unwrap_or_else(|_| {
        panic!("missing setup file at {path}; run bivariatekzg_test_setup first")
      });
    let mut reader = BufReader::new(file);
    
    let poly = (0..n)
      .map(|_| <E as Engine>::Scalar::random(OsRng))
      .collect::<Vec<_>>();
    let point = (0..log_n)
      .map(|_| <E as Engine>::Scalar::random(OsRng))
      .collect::<Vec<_>>();

    let ck = <E as Engine>::CE::load_setup(&mut reader, LABEL, n).unwrap();

    let (pk, vk) = ChopinEvaluationEngine::<E>::setup(&ck).unwrap();

    let eval = MultilinearPolynomial::new(poly.clone()).evaluate(&point);

    let comm = <E as Engine>::CE::commit(&ck, &poly, &<E as Engine>::Scalar::ZERO);

    let mut prover_transcript = <E as Engine>::TE::new(b"chopin-from-setup");
    let proof = ChopinEvaluationEngine::<E>::prove(
      &ck,
      &pk,
      &mut prover_transcript,
      &comm,
      &poly,
      &point,
      &eval,
    )
    .unwrap();

    let mut verifier_transcript = <E as Engine>::TE::new(b"chopin-from-setup");
    ChopinEvaluationEngine::<E>::verify(
      &vk,
      &mut verifier_transcript,
      &comm,
      &point,
      &eval,
      &proof,
    )
    .unwrap();

    println!("Chopin proof verified with loaded setup (log_n={log_n}, n={n})");
  }
}
